### ISSUE TITLE
MacOS version does not work

### ISSUE THREAD

**Issue by bdentino** [kubepack/onessl#8]
Release binary from https://github.com/kubepack/onessl/releases/download/0.1.0/onessl-darwin-amd64 immediately fails with `Killed: 9` (exit code 137). Any debugging tips? I am trying to set up voyager but the installation guide requires this binary.

**Comment by bdentino** [comment]
Resolved by building locally from source and using that binary. Probably just a problem with my environment.

**Comment by tamalsaha** [comment]
This was a problem in the build tool upx . I have fixed this issue and explained the issue here:https://github.com/kubepack/onessl/issues/9#issuecomment-366780500
